include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    todo: ignore
    non_constant_identifier_names: ignore
    library_private_types_in_public_api: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    prefer_relative_imports: true